services:
  nginx:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./www:/srv/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - www
  phpfpm:
    image: php:fpm-alpine
    volumes:
      - ./www:/srv/www
    networks:
      - www
  # MariaDB Service
  mariadb:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: your_password
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - www
  # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8081:80
    environment:
      PMA_HOST: mariadb
    depends_on:
      - mariadb
    networks:
      - www
# Volumes
volumes:
  mysqldata:
networks:
  www:
